### List Articles lists
GET localhost:8080/api/articlesLists

### List Articles list by id
GET localhost:8080/api/articlesLists/2

### Update Articles list articles
PATCH localhost:8080/api/articlesLists/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "articles":[
    {
      "id": 3,
      "date": "2023-07-08",
      "title": "Article 3: article title",
      "subtitle": null,
      "content": "b Content data of article 3. Article 3 explores the issues regarding the problems without solutions on current days"
    },
    {
      "id": 1,
      "date": "2023-06-30",
      "title": "Article 1: article title",
      "subtitle": "This is article 1 brief explanation",
      "content": "a Content data of article 1. Article 1 explores the issues regarding the problems without solutions on current days"
    },
    {
      "id": 5,
      "date": "2023-07-10",
      "title": "Article 5: article title",
      "subtitle": null,
      "content": "e Content data of article 5. Article 5 explores the issues regarding the problems without solutions on current days"
    }
  ]
}

### Update Articles list name
PATCH localhost:8080/api/articlesLists/1
Content-Type: application/json
Authorization: Bearer {{token}}

  {
    "name": "Favorites 2"
  }

### Creates Articles List
POST localhost:8080/api/articlesLists
Content-Type: application/json
Authorization: Bearer {{token}}

  {
    "name": "Read later 2"
  }

### Deletes the articles list by ID
DELETE localhost:8080/api/articlesLists/3
Authorization: Bearer {{token}}