### List users
GET localhost:8080/api/users

### Create user
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Giovanne Bressam",
  "email": "giovannebressam@gmail.com",
  "password": "password"
}

### List user by id
GET localhost:8080/api/users/2

### List current logged in user
GET localhost:8080/api/users/me
Authorization: Bearer {{token}}

### Login as usual user
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "giovannebressam@gmail.com",
  "password": "password"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Login as admin user
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "admin@authserver.com",
  "password": "admin"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Deletes user
DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}
